In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
def create_board():
    board = np.zeros((6,7))
    return board


In [3]:
board = create_board()
print(board)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
game_over = False
